export default {
    inherit: {
        type: 'ww-text',
        exclude: ['text'],
    },
    editor: {
        label: { en: 'Form Input', fr: 'Entrée de Formulaire' },
        customStylePropertiesOrder: [
            'placeholderColor',
            'advancedPlaceholder',
            'forceAnimation',
            ['placeholderPosition', 'placeholderScaling', 'positioningAjustment', 'transition', 'timingFunction'],
        ],
    },
    triggerEvents: [
        { name: 'change', label: { en: 'On change' }, event: { value: '' }, default: true },
        { name: 'initValueChange', label: { en: 'On init value change' }, event: { value: '' } },
    ],
    properties: {
        placeholderColor: {
            label: {
                en: 'Placeholder color',
            },
            type: 'Color',
            options: {
                nullable: true,
            },
            bindable: true,
            responsive: true,
            states: true,
            defaultValue: '#000000ad',
            hidden: content => content.advancedPlaceholder,
        },
        advancedPlaceholder: {
            label: 'Advanced placeholder',
            type: 'OnOff',
            defaultValue: false,
        },
        forceAnimation: {
            label: { en: 'Force animation' },
            type: 'OnOff',
            defaultValue: false,
            hidden: content => !content.advancedPlaceholder,
        },
        placeholderPosition: {
            label: { en: 'Active position' },
            type: 'TextSelect',
            options: {
                options: [
                    { value: 'inside', label: { en: 'Inside' } },
                    { value: 'outside', label: { en: 'Outside' } },
                ],
            },
            responsive: true,
            defaultValue: 'outside',
            hidden: content => !content.advancedPlaceholder,
        },
        placeholderScaling: {
            label: { en: 'Active size' },
            type: 'Number',
            options: { min: 0, max: 1, step: 0.1 },
            responsive: true,
            defaultValue: 0.8,
            hidden: content => !content.advancedPlaceholder,
        },
        positioningAjustment: {
            type: 'Length',
            label: {
                en: 'Active margin',
            },
            options: {
                unitChoices: [{ value: 'px', label: 'px', min: 0, max: 500 }],
            },
            responsive: true,
            defaultValue: '0px',
            hidden: content => !content.advancedPlaceholder,
        },
        transition: {
            type: 'Length',
            label: {
                en: 'Transition',
            },
            options: {
                unitChoices: [{ value: 'ms', label: 'ms', min: 0, max: 2000 }],
            },
            responsive: true,
            defaultValue: '400ms',
            hidden: content => !content.advancedPlaceholder,
        },
        timingFunction: {
            label: { en: 'Timing function' },
            type: 'TextSelect',
            options: {
                options: [
                    { value: 'cubic-bezier(0, 1.08, 0.76, 1)', label: { en: 'auto' } },
                    { value: 'ease', label: { en: 'ease' } },
                    { value: 'ease-in', label: { en: 'ease-in' } },
                    { value: 'ease-out', label: { en: 'ease-out' } },
                    { value: 'ease-in-out', label: { en: 'ease-in-out' } },
                    { value: 'linear', label: { en: 'linear' } },
                ],
            },
            defaultValue: 'cubic-bezier(0, 1.08, 0.76, 1)',
            hidden: content => !content.advancedPlaceholder,
        },
        value: {
            label: {
                en: 'Init value',
            },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: '',
        },
        type: {
            label: { en: 'Input type', fr: 'Input type' },
            type: 'TextSelect',
            options: {
                options: [
                    { value: 'text', label: { en: 'Short answer', fr: 'Texte' } },
                    { value: 'textarea', label: { en: 'Long answer', fr: 'Texte' } },
                    { value: 'email', label: { en: 'Email', fr: 'Email' } },
                    { value: 'password', label: { en: 'Password', fr: 'Mot de passe' } },
                    { value: 'number', label: { en: 'Number', fr: 'Nombre' } },
                    { value: 'decimal', label: { en: 'Decimal', fr: 'Decimal' } },
                    { value: 'date', label: { en: 'Date', fr: 'Date' } },
                    { value: 'time', label: { en: 'Time', fr: 'Heure' } },
                    { value: 'tel', label: { en: 'Phone', fr: 'Téléphone' } },
                ],
            },
            section: 'settings',
            defaultValue: 'text',
        },
        displayPassword: {
            label: {
                en: 'Display password',
            },
            section: 'settings',
            type: 'OnOff',
            bindable: true,
            defaultValue: false,
            hidden: content => content.type !== 'password',
        },
        readonly: {
            label: { en: 'Read only', fr: 'Lecture seule' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: false,
            hidden: (content, sidePanelContent, boundProps, wwProps) => !!(wwProps && wwProps.readonly !== undefined),
        },
        required: {
            label: { en: 'Required', fr: 'Requis' },
            type: 'OnOff',
            section: 'settings',
            defaultValue: true,
            bindable: true,
        },
        precision: {
            label: { en: 'Precision', fr: 'Precision' },
            type: 'TextSelect',
            options: {
                options: [
                    { value: '0.1', label: { en: '1.0' } },
                    { value: '0.01', label: { en: '1.00' } },
                    { value: '0.001', label: { en: '1.000' } },
                    { value: '0.0001', label: { en: '1.0000' } },
                    { value: '0.00001', label: { en: '1.00000' } },
                    { value: '0.000001', label: { en: '1.000000' } },
                    { value: '0.0000001', label: { en: '1.0000000' } },
                    { value: '0.00000001', label: { en: '1.00000000' } },
                ],
            },
            section: 'settings',
            hidden: content => content.type !== 'decimal',
            defaultValue: '0.1',
        },
        placeholder: {
            label: { en: 'Placeholder', fr: 'Placeholder' },
            type: 'Text',
            options: { placeholder: 'Type text' },
            section: 'settings',
            hidden: content => content.type === 'date' || content.type === 'time',
            multiLang: true,
            bindable: true,
            defaultValue: {},
        },
        rows: {
            label: { en: 'Rows', fr: 'Rows' },
            type: 'Number',
            options: { min: 1, max: 25 },
            section: 'settings',
            hidden: content => content.type !== 'textarea',
            defaultValue: 4,
        },
        resize: {
            label: { en: 'Resize', fr: 'Resize' },
            type: 'OnOff',
            hidden: content => content.type !== 'textarea',
            defaultValue: false,
        },
        min: {
            label: { en: 'Min number', fr: 'Min number' },
            type: 'Number',
            options: { min: 0, max: 100 },
            section: 'settings',
            hidden: content => content.type !== 'number' && content.type !== 'decimal',
            defaultValue: '0',
            bindable: true,
        },
        max: {
            label: { en: 'Max number', fr: 'Max number' },
            type: 'Number',
            options: { min: 0, max: 10000 },
            section: 'settings',
            hidden: content => content.type !== 'number' && content.type !== 'decimal',
            defaultValue: '10000',
            bindable: true,
        },
        hideArrows: {
            label: { en: 'Hide arrows', fr: 'Masquer les flèches' },
            type: 'OnOff',
            section: 'settings',
            hidden: content => content.type !== 'number' && content.type !== 'decimal',
            defaultValue: false,
        },
        placeholderElement: {
            hidden: true,
            defaultValue: null,
        },
    },
};
